### ISSUE TITLE
infraction reports e-mailed to users do not contain response directions 

### ISSUE THREAD

**Issue by DonCragun** [unixneo/unix.com.bugtracker#1]
Reports of infractions sent to users posted in the unix.com user infractions forum all include a final paragraph that says "If you would like to discuss this moderation action, please cut-and-paste this message into a new post in the meeting room forum. Please do not reply to this via private message. Thank you." but the private message sent to the user who has been given an infraction does not include the quoted text.

If we want users to follow these directions (and I think we do) want them to), these directions should be included in the infraction notice that is sent to the user.

The complete text of the last infraction notice I received was the following:

**Comment by unixneo** [comment]
Thanks.  Truncated message (as I have many examples of this message) and will look into it.

**Comment by unixneo** [comment]
Here is the original message text from the DB

```
Dear $infraction[username],

This is a reminder from the moderators at $vboptions[bbtitle].

Reason: $infraction[reason]
-------
$infraction[message]
-------

This reminder is worth $infraction[points] point(s) and may result in restricted access until it expires.  Please reread the forum rules if you have forgotten or neglected to read them.  The forum rules are important for the entire community.

Original Post:
$infraction[post]
[quote]$infraction[pagetext][/quote]

Thanks for contributing!

$vboptions[bbtitle]
```

I change it to:

```
Dear $infraction[username],

This is a reminder from the moderators at $vboptions[bbtitle].

Reason: $infraction[reason]
-------
$infraction[message]
-------

This reminder is worth $infraction[points] point(s) and may result in restricted access until it expires.  Please reread the forum rules if you have forgotten or neglected to read them.  The forum rules are important for the entire community.

If you would like to discuss this moderation action, please cut-and-paste this message into a new post in the [url=$vboptions[bburl]/meeting-room/]meeting room forum[/url]. Please do not reply to this via private message. Thank you.

Original Post:
$infraction[post]
[quote]$infraction[pagetext][/quote]

Thanks for contributing!

$vboptions[bbtitle]```
